package kr.or.connect.reservation.dao.sql;

public class ProductDaoSql {
	public static final String SELECT_PRODUCTS_ALL = "SELECT product.id as product_id, product.description as product_description, product.content as product_content, display_info.id as display_info_id, display_info.place_name as place_name, file_info.save_file_name as product_image_url FROM product LEFT JOIN display_info ON product.id = display_info.product_id LEFT JOIN product_image ON product.id = product_image.product_id LEFT JOIN file_info ON product_image.file_id = file_info.id WHERE product_image.type = :imageType ORDER BY product.id limit :start, :limit";
	public static final String SELECT_PRODUCTS_BY_CATEGORY_ID = "SELECT product.id as product_id, product.description as product_description, product.content as product_content, display_info.id as display_info_id, display_info.place_name as place_name, file_info.save_file_name as product_image_url FROM product LEFT JOIN display_info ON product.id = display_info.product_id LEFT JOIN product_image ON product.id = product_image.product_id LEFT JOIN file_info ON product_image.file_id = file_info.id WHERE product.category_id = :categoryId AND product_image.type = :imageType ORDER BY product.id limit :start, :limit";
	public static final String SELECT_COUNT_ALL = "SELECT count(*) FROM product LEFT JOIN display_info ON product.id = display_info.product_id ";
	public static final String SELECT_COUNT_BY_CATEGORY_ID ="SELECT count(*) FROM product LEFT JOIN display_info ON product.id = display_info.product_id WHERE product.category_id = :categoryId";
	public static final String SELECT_FILE_INFO_BY_CATEGORY_ID = "SELECT file_info.id, file_info.file_name, file_info.save_file_name, file_info.content_type, file_info.delete_flag, file_info.create_date, file_info.modify_date FROM product LEFT JOIN display_info ON product.id = display_info.product_id LEFT JOIN product_image ON product.id = product_image.product_id LEFT JOIN file_info ON product_image.file_id = file_info.id WHERE product.category_id = :categoryId AND display_info.id = :displayInfoId AND product_image.type = :imageType";
	public static final String SELECT_FILE_INFO_ALL = "SELECT file_info.id, file_info.file_name, file_info.save_file_name, file_info.content_type, file_info.delete_flag, file_info.create_date, file_info.modify_date FROM product LEFT JOIN display_info ON product.id = display_info.product_id LEFT JOIN product_image ON product.id = product_image.product_id LEFT JOIN file_info ON product_image.file_id = file_info.id WHERE display_info.id = :displayInfoId AND product_image.type = :imageType";
}
